### PR TITLE
Remove contextual-typing

### PR DESCRIPTION
**Pull request by szagi3891**

### CODE REVIEW

**Comment by danielnixon** [comment]
Hi @szagi3891 thanks for the PR! You can see that removing the contextual type check breaks a few tests:

https://travis-ci.org/github/danielnixon/eslint-plugin-total-functions/builds/723661249

Some examples that break:

```ts
const arr = [0]; const foo = arr[0] as number | undefined;
```

```ts
const last: <A>(array: ReadonlyArray<A>) => A | undefined = (a) => a[a.length - 1];
```

I'd like for these to remain _not_ flagged by this rule. Does the change in https://github.com/danielnixon/eslint-plugin-total-functions/commit/3c332c1ed68b553d1085834e18f21989410c4883 do what you need?

**Comment by szagi3891** [comment]
Yes, that's what I meant. I would like the linter to show me these cases as well.

Will this fix work for Record as well?

**Comment by danielnixon** [comment]
>Yes, that's what I meant. I would like the linter to show me these cases as well.

Ah that's interesting. These cases are actually safe (unless I'm missing something). They're not like the example from https://github.com/danielnixon/eslint-plugin-total-functions/issues/68 where definite assignment analysis forces our hand.

If they're safe, why do you want the linter to flag them? For consistency's sake? For some other reason?

**Comment by szagi3891** [comment]
Unfortunately these cases are also dangerous. Here's a piece of code that also demonstrates this case:

```
    const uuu: Record<string, number> = {};
    const uuu2: number | undefined = uuu.ggg;
    const uuu3: number = uuu2;
```

**Comment by danielnixon** [comment]
If you upgrade to v3.0.0 you'll find `uuu.ggg` is flagged as unsafe now :)

**Comment by szagi3891** [comment]
Did you send this new version to the npm?

**Comment by szagi3891** [comment]
Fantastic. Thank you :)

**Comment by danielnixon** [comment]
I'll close this in favour of https://github.com/danielnixon/eslint-plugin-total-functions/issues/68

Thanks again for spotting the issue @szagi3891

**Pull request closed without merging**
